name: Native Builds

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: edge
            asset: edge-linux-x86_64

          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: edge.exe
            asset: edge-windows-x86_64.exe

          - name: Mac
            os: macos-latest
            target: aarch64-apple-darwin
            binary: edge
            asset: edge-macos-aarch64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: compiler

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, clippy

      - name: Install target
        run: rustup target add ${{ matrix.target }}
        working-directory: compiler

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: compiler

      - name: Size
        run: ls -lh target/${{ matrix.target }}/release/${{ matrix.binary }}
        shell: bash
        working-directory: compiler

      - name: Test
        run: cargo test
        working-directory: compiler

      - name: Install CLI Tools
        run: cargo install cargo-shear cargo-bloat
        working-directory: compiler

      - name: Unused Code
        run: cargo shear && cargo clippy --target ${{ matrix.target }}
        working-directory: compiler

      - name: Bloat
        run: cargo bloat --release --target ${{ matrix.target }} --crates -n 7
        working-directory: compiler

      - name: Rename for release
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: cp compiler/target/${{ matrix.target }}/release/${{ matrix.binary }} ${{ matrix.asset }}

      - name: Upload Native Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset }}
          fail_on_unmatched_files: true