name: Deployment Pipeline

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

jobs:
  native:
    name: Native Builds
    permissions:
      contents: write
    uses: ./.github/workflows/native.yml
    secrets: inherit

  wasm:
    name: WebAssembly
    permissions:
      contents: write
    uses: ./.github/workflows/wasm.yml
    secrets: inherit

  demo:
    name: Deploy Demo (GitHub Pages)
    uses: ./.github/workflows/demo.yml
    secrets: inherit