name: pipeline

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

jobs:
  native:
    permissions:
      contents: write
    uses: ./.github/workflows/native.yml
    secrets: inherit

  wasm:
    permissions:
      contents: write
    uses: ./.github/workflows/wasm.yml
    secrets: inherit