# .cargo/config.toml

[target.wasm32-unknown-unknown]
rustflags = [
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Zunstable-options",
    "-Cpanic=immediate-abort",
]

[unstable]
build-std = ["core", "alloc", "panic_abort"]